version: '3.8'

services:
  ubuntu_dev:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: ubuntu_2204_devcontainer
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspace  # 호스트 프로젝트 루트를 컨테이너에 마운트
